### ISSUE TITLE
not working on firefox

### ISSUE THREAD

**Issue by TheTerrorByte** [RealDebugMonkey/ZeachCobbler#12]
keycodes no work, and chrome is a virus that wipes my OS off my disk.

**Comment by Gjum** [comment]
Yeah, Chrome is the pure evil. That's why I use Chromium.

**Comment by RealDebugMonkey** [comment]
Several attempts have been made to get the script working on Firefox but issue after issue crop up.
I'd like to get it working, but it's not happening unless I end bored with a lot of time on my hands, or if someone else figures out the compatibility issues.
