### ISSUE TITLE
Script does not work anymore | agar.io change of UI/login

### ISSUE THREAD

**Issue by Szigerd** [RealDebugMonkey/ZeachCobbler#17]
agar.io changed UI, now login with fuckin' Facebook or play as guest. With script activated no play possible.

![image](https://cloud.githubusercontent.com/assets/13200024/8592811/8b735d28-2632-11e5-97b2-ae23ca3811b0.png)

**Comment by Viliusx** [comment]
Same problem =(. But instead I see blobs, leaderboard, pellets etc everything in background. But I can't play =((

**Comment by RealDebugMonkey** [comment]
Made some quick hacks to get it working for guest play. Facebook and party play are still broken and will be till I get some more time

**Comment by RealDebugMonkey** [comment]
Should be all good now
