### ISSUE TITLE
It still suicides with Viruses

### ISSUE THREAD

**Issue by ferris1988** [RealDebugMonkey/ZeachCobbler#18]
When getting bigger it destroys himself going into viruses

**Comment by RealDebugMonkey** [comment]
Yes, I've seen it do that too. I'll have to figure out how to get it to just go around without trying to play bumpercars first.

**Comment by Szigerd** [comment]
if(el.isVirus) {
                        if(zeach.myPoints.length >= 16 ) {
                            // Can't split anymore so viruses are actually a good food!
                            delete vec.gr_type; //vec.gr_type = null;
                        } else {
                            // Hate them a bit less than same-sized blobs.
                            dist *= 2;
                        }

Try dist *=1 or 1.2. I tried it and it worked well for me. Why hate them less? Reasoning behind this? Just a 'constant' in the model, subject to change.

**Comment by Szigerd** [comment]
urbandictionary: Bumper Cars, top definition
When two lesbians have sex. Nothing goes in or out, just a lot of bumping of things.
Paula and this slut went to play bumper cars...and I watched them play all night...

Learning all the time :)

**Comment by AngelMarquez** [comment]
I haven't had time to look at or work on this ... so for now just going to take @Szigerd 's suggestion and just change dist += to 1.2 ... hopefully that will help cause less suicides all around. Should be in next release.

**Comment by RealDebugMonkey** [comment]
I haven't had time to look at or work on this ... so for now just going to take @Szigerd 's suggestion and just change dist += to 1.2 ... hopefully that will help cause less suicides all around. Should be in next release.
