### ISSUE TITLE
Need to keep chrome maximized?

### ISSUE THREAD

**Issue by adamfire** [RealDebugMonkey/ZeachCobbler#25]
Hi

Can I minimize chrome and it will still work or I must have maybe just little window with active tab?

I run this on server and minimizing can lower using resources.

**Comment by alepacheco** [comment]
From my personal experience I had notice some delay when the windows is minimized. 
How can I run the script in a server? Thanks

**Comment by adamfire** [comment]
In a server with windows on this of course ;) I don't want to leave my pc
on night to see how bot work in longer term.

When maximized it's 100% use of cpu.

When minimized it's about 10%.

2015-07-14 11:26 GMT+02:00 Alejandro Pacheco Bobillo <
notifications@github.com>:

**Comment by RealDebugMonkey** [comment]
I've tried this using Chrome in both Windows and on OSX. Everything works just fine on OSX. On Windows it seems to work fine for a while but it ended up freezing on me when I switched tabs after a while.

**Comment by adamfire** [comment]
Ok, thanks for answer :)
