### ISSUE TITLE
Virus eaten counter issue and "vanilla end-game stats"

### ISSUE THREAD

**Issue by toto2379** [RealDebugMonkey/ZeachCobbler#32]
1. Whenever I eat a virus, it counts as a cell eaten instead of a virus eaten.
2. The vanilla version of agar.io now shows a "match results" box on death instead of the regular menu which shows a leaderboard time, mass over time and other stuff.
   But ZeachCobbler doesn't show it, no matter if the show stats box option is on or off.

**Comment by RealDebugMonkey** [comment]
Issue fixed: Viruses are now counted correctly in ZC stats. 
Official Stats will eventually be integrated, but the code to display those has not been added.
