### ISSUE TITLE
bit.do and connect.agariomods.com skin support dont work

### ISSUE THREAD

**Issue by ghost** [RealDebugMonkey/ZeachCobbler#41]
Hello all!
Firstly, I must say, Zeach Cobbler is the best mod for current agar.io. Also i think the built-in grazing bot is better than Apostolique's bot! Good work!
To the problem, the bit.do skin support dont work. I tried nick "`Pepin" (bit.do/Pepin - it redirects to http://i.imgur.com/rtB4gTp.png), but in-game, i dont see the skin. I also tried the "`roborex" nick, but it dont work too.

**EDIT**: connect.agariomods.com skins for me doesnt work too. I upload an avatar to account "Pepin", but when in-game i dont see any skin! But the agariomods.com extended skins working...

**Comment by RealDebugMonkey** [comment]
I removed the bit.do skins after agariomods.com connect skins came out.

As far as the agariomods skins, you have to prepend an asterisk in front of the name. So your name isn't Pepin. It's *Pepin -- See here: http://i.imgur.com/bl5bCsV.png

I do need the remove the bit.do part from the readme. Thanks for letting me know.
