### ISSUE TITLE
Self Destruct, non-existent any more?

### ISSUE THREAD

**Issue by M1kep** [RealDebugMonkey/ZeachCobbler#49]
So I was reading the main page/README and it says, "8 - Self destruct (spectacular when you're really big)" yet I can't find it in the code anywhere, and pressing '8' does nothing for me :/

**Comment by ghost** [comment]
Same.

**Comment by Gjum** [comment]
Self destruct was disabled on official servers. I'm not sure, but Ogar might support it.

**Comment by RealDebugMonkey** [comment]
yep, sorry ... was removed
