### ISSUE TITLE
(not really an issue) but clarification/request

### ISSUE THREAD

**Issue by NubileEye** [RealDebugMonkey/ZeachCobbler#50]
How do I disable the darkened mode that is auto enabled? I didn't see an option for it in settings.

http://i.imgur.com/2NaLyNF.png <- That's what I'm talking about. The colors, etc. I'd like the background to be white and all of that.

**Comment by NubileEye** [comment]
It was within the vanilla settings. The mod switched it on, though.

**Comment by RealDebugMonkey** [comment]
@NubileEye sorry for the delayed response. I made the switch to auto-dark ages ago (since it's my preference). This was before I had any code in there to save settings. I should go ahead and remove that code now and just make the setting persist across sessions along with all the other settings.

**Comment by DaddyG55** [comment]
I really enjoy using Zeech Cobbler. However, Igar.io must've updated their code recently. Zeech Cobbler loads, but I cannot move at all.
