### ISSUE TITLE
Cell unable to move

### ISSUE THREAD

**Issue by ghost** [RealDebugMonkey/ZeachCobbler#51]
As of August 11th, if Zeach Cobbler is enabled, the cell is unable to move even when the grazer is on.

**Comment by roessland** [comment]
+1. It worked just fine this morning, but not anymore.

**Comment by KaidenP** [comment]
+1 same here. confirm it works fine w/o the script.

**EDIT:** Tried again and it working now.
**EDIT2:** Not working again. Perhaps agario is pushing updates to the servers slowly (so some are updated, but not all), and this update breaks zeach?

**Comment by NubileEye** [comment]
I know I'm just jumping onto the bandwagon, but it's the same way. I was trying all sorts of configurations trying to get it to work. Turning adblock on/off, but I can't even move period. (With the grazer on/off)

**Comment by ajenkul** [comment]
Same problem, any one know how to make it move?

**Comment by RealDebugMonkey** [comment]
Sorry guys. officially broken as of today. I'll try to fix it tomorrow!

**Comment by RealDebugMonkey** [comment]
I can use Apostolique's changes as a guide ... https://github.com/Apostolique/Agar.io-bot/commit/d933ecfe4f8ef16d9ddd66d46868157e4e59718b#diff-07964d7e881aff01527bc2acbb3edf74

I should be able to knock it out tomorrow. Sorry for the inconvenience guys!

**Comment by RealDebugMonkey** [comment]
nevermind. it was easier than i thought about to push a fix

**Comment by RealDebugMonkey** [comment]
0.28.4 pushed and has the issue fixed. 
Be sure to turn multiblob off. Zeach removed that feature ... i'll have to remove the multiblob code when time allows.

**Comment by RealDebugMonkey** [comment]
prior fix had a bug. 0.28.5 pushed with a fix.

**Comment by ajenkul** [comment]
Thanks you very much for hot fix
