### ISSUE TITLE
[Request] Enable/Disable Selected Keys

### ISSUE THREAD

**Issue by QuasarX** [RealDebugMonkey/ZeachCobbler#53]
Please add this feature. We can use another scripts with this script.
Example: auto shot with E button using another script.

**Comment by ghost** [comment]
I dont understand. Can you please explain what?

**Comment by QuasarX** [comment]
Bro I using for "e" button macro code. (https://greasyfork.org/tr/scripts/10904-agar-mass-ejector)
I can not use this script with your script. Because using "e" key these scripts.

**Comment by ghost** [comment]
@QuasarX its hard to edit "E" key from your script?

**Comment by QuasarX** [comment]
Bro edit easy but; happening easy playing.  Best key ( e ) for mass eject.

**Comment by ghost** [comment]
@QuasarX so edit the key in zeach cobbler....

**Comment by QuasarX** [comment]
ok bro I try this but you can make GUI, will be awesome

**Comment by RealDebugMonkey** [comment]
PepinZ thanks for trying to handle this. You're a champ

**Comment by ghost** [comment]
@QuasarX In options you have Keyboard Binds tab... https://github.com/PepinCZ/ZeachCobbler, I also created pull request, hopefuly it will be in ZeachCobbler soon.

**Comment by QuasarX** [comment]
Thanks.
