### ISSUE TITLE
[Request] Auto Load Game Mode

### ISSUE THREAD

**Issue by QuasarX** [RealDebugMonkey/ZeachCobbler#54]
This code work with browser console
setGameMode(":experimental");

How to add this code your script?

**Comment by ghost** [comment]
@QuasarX please learn some javascript basics.

**Comment by QuasarX** [comment]
Bro I already inserted my codes in your script

$("#nick").val("MyNick"); // Set username here
$('#settings, #instructions').toggle();return false; // Settings open

But how to add game mode select, code? Please help :/

**Comment by kaue** [comment]
```
$('#gamemode').val(':teams')
```

### Avaliable values:
- :teams
- :experimental
- :party

**Comment by QuasarX** [comment]
Thanks @kauegimenes

Bro this work but not connecting changed server (experimental)
Only showing server name

**Comment by RealDebugMonkey** [comment]
If you want to do your own customization i'd look in the code for the place where keybindings are set and just add a custom keybinding for an unassigned letter and you can issue that command with a keystroke.

**Comment by QuasarX** [comment]
Not active anymore
