### ISSUE TITLE
What is the licence?

### ISSUE THREAD

**Issue by Yukkcake** [RealDebugMonkey/ZeachCobbler#55]
What is the licence of this project?
If I redistribute a modified version, what license should I use?

**Comment by RealDebugMonkey** [comment]
I think because I sorta-kinda got the basis of the mini-map code from GamerLio and he decided to use GPLv2 then that makes mine GPLv2 by default. https://github.com/heyitsleo/agar.io-bot/blob/master/LICENSE

My personal preference is MIT/BSD/Apache ... but these things can get kind of murky

**Comment by RealDebugMonkey** [comment]
Closing. I'll add the appropriate license info to the repo when i get time.
