### ISSUE TITLE
ZeachCobbler won't do anything.

### ISSUE THREAD

**Issue by Fernystar** [RealDebugMonkey/ZeachCobbler#56]
The starting screen shows all the options and lets me play the game but it won't do anything other than that.  None of the features work

![](http://i.imgur.com/sEAWfFP.png)

**Comment by ghost** [comment]
I don't understand what is your problem. For me works everything...

**Comment by Fernystar** [comment]
Well it won't do any of the features except show me the options.  I tried all the buttons that are supposed to activate stuff however nothing happens.  I installed ZeachCobbler and then tried the PepinCZ mod afterwards(Not at the same time) neither worked or did anything.

**Comment by Fernystar** [comment]
Never mind it was some mod I'd installed months ago.  I didn't notice it because it was broken and never worked.  Uninstalling that mod let me use the pepin mod just fine.

**Comment by ghost** [comment]
@Fernystar ok please close the thread :)
