### ISSUE TITLE
Contacts

### ISSUE THREAD

**Issue by ethedev** [RealDebugMonkey/ZeachCobbler#57]
Hello please can i have your skype or any method to live chat maybe gitter too at: https://gitter.im/user8261200114280/JonMTG ? i have a question about something related to this development.
Thanks in advace!

**Comment by RealDebugMonkey** [comment]
Sorry for my long absence. Burnout's a bitch. You can find me in the #agariomods chatroom in IRC on the rizon irc network. I go by DebugMonkey there.

Please note that the #agariomods room has a registration requirement, so you'll need to register before you're allowed into the chatroom.

If you don't want to register then feel free to just send me a private message. Just make sure you mention ZeachCobbler or else I'll ignore it, as I get tons of random messages
