### ISSUE TITLE
Just a noobs javascript question about ',' and ';' use in the code ...

### ISSUE THREAD

**Issue by ghost** [RealDebugMonkey/ZeachCobbler#58]
On line 159, why do you use a ',' instead of a ';' at the end of the line ?

I tried to find some explanation on the net... but I don't really understand the difference here... 

line 159 : cobbler[backingVar] = GM_getValue(settingName, defaultValue),

ps : with the 'automatic indent' function of the tampermonkey javascript editor, it was making my understanding of code harder (for me as a pure javascript beginner) because the indentation was not good, adding ident on the following line.

ps : thanks for your great work ! I'm learning javascript with great fun playing with your code and trying to add new functionalities :-)

**Comment by kaue** [comment]
I think it should be a `;` its probably a typo

**Comment by RealDebugMonkey** [comment]
@kauegimenes is completely correct. Just a typo. Luckily it still works the same in the end. Code is now updated with semicolon. 

@ilboued If you end up doing a lot of javascript, I highly recommend webstorm: https://www.jetbrains.com/webstorm/
I paid the $50 for the individual developer license, but it's totally made up for it in the time i saved by not wasting inside tampermonkey's editor.

**Comment by ghost** [comment]
roger & thanks :)
