### ISSUE TITLE
[Request] OGARio Features

### ISSUE THREAD

**Issue by QuasarX** [RealDebugMonkey/ZeachCobbler#61]
Please add **OGARio** features;
http://ogario.wpload.com/

+Minimap (**sectors**, location, **location coordinates, death location**)
+Background sectors
+Leaderbord nicknames copy

Thanks. You are awesome.

**Comment by ghost** [comment]
The background selector could be nice, I could implement that. And minimap with location, location coordinates is already in Zeach Cobbler.

**Comment by QuasarX** [comment]
Yes, I mean sector codes. **Ex;** A1, B7
**Sectors, Death location, Background sectors** features will be very good.

**Comment by ghost** [comment]
@QuasarX sorry I havent got time now, but why implement "selectors"? I think is for one person absolutly useless. Different situation will be if 2 and more players playing on the same server and they are "finding", in this case It could be probably usefull, but still, coordiantes for better.

**Comment by Yukkcake** [comment]
The Sectors is useful because when you going to tell you friend your location,
"E5" is better than something like "(5234, 4535)"

**Comment by ghost** [comment]
@Yukkcake its pointless search your friend in agar, but... ye, lets say its awesome.

**Comment by RealDebugMonkey** [comment]
Honest question here: Why not just use OGARio? Doesn't it have most (if not all) of the same features? I'm honestly curious.

**Comment by QuasarX** [comment]
@RealDebugMonkey ZeachCobbler best than other scripts. But other scripts some features very good.

**Comment by ghost** [comment]
@RealDebugMonkey yea I agree. We really arent here to just copy features.

**Comment by QuasarX** [comment]
Not active anymore
