### ISSUE TITLE
[Suggestion] Add feeder bots

### ISSUE THREAD

**Issue by toto2379** [RealDebugMonkey/ZeachCobbler#66]
Recently I have learned about free scripts(unlike raga) that can summon bots to feed/help you, two of these scripts are "agario powerups" from the chrome web store and this : 
https://github.com/Apostolique/AposFeedingBot

It is possible to add as many bots as you want in private servers, but the number of bots is restricted to 4 in Party mode, and restricted to zero in other modes.

So I wonder if it could be possible to add this functionality to ZeachCobbler?

If yes, then can you add hotkeys to make these bots split and eject mass, and the option to make these bots follow the mouse cursor?

**Comment by ghost** [comment]
I think better will be add hid launcher...

**Comment by ghost** [comment]
Anyway: what are doing the feeder bots? How helping you?

**Comment by toto2379** [comment]
These feeder bots are commonly seen in Party mode
The feeder bots can go to my direction and feed me by suiciding into me. But after I gain 600 mass I have to combine the bots so that they can still give me mass ; bots that haven't eaten any cell can't give mass to anyone with  over 600 mass.

Once I saw a video of someone using the feeder bots as a teammate(but the script isn't public), he was teaming with a bot that he controlled and had the advantages of teamers while playing "solo", like faster recombine, fast mass exchanging, virus eating, etc. - so that's why I suggest that the bots can split and eject mass.
