### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by ghost** [RealDebugMonkey/ZeachCobbler#68]
Hello,
I recently found this bug. I can't connect to server. I found in console this:
XMLHttpRequest cannot load https://m.agar.io/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://agar.io' is therefore not allowed access. The response had HTTP status code 522.

And similar errors.... Some agar.io update or agar.io failure?

**Comment by CollaboratingElephant** [comment]
Found any fix?
