### ISSUE TITLE
Facebook starting mass will stop working after some time

### ISSUE THREAD

**Issue by Rufus66** [RealDebugMonkey/ZeachCobbler#71]
If I play the game vanilla with no mods this will not happen, I will always start with extra mass.

After a few deaths while playing with ZC or after leaving grazing mode on with auto respawn (page will crash some memory issue if I leave afk for too long) It will still show as being logged into facebook, and I can log in and out of facebook. But I will always start with 10 mass for approx 1 hour after it happens even if I switch back to vanilla agar.
I can tell it will happen because the ammount of coins I have will change to a dash ( - )

**Comment by RealDebugMonkey** [comment]
The fact that it happens in vanilla agar points to a problem on Facebook's side. There's not much I can do to help there... sorry :(
