### ISSUE TITLE
Recent Error

### ISSUE THREAD

**Issue by DaddyG55** [RealDebugMonkey/ZeachCobbler#72]
I'm receiving "Uncaught RangeError: Offset is outside the bounds of the DataView" quite a bit lately. Seems to be occuring during the rb(a) and sb(a, c) functions.

**Comment by RealDebugMonkey** [comment]
Is this still happening as of  v0.31.5 ?

**Comment by DaddyG55** [comment]
No, seems to be fixed. Thank you!
