### ISSUE TITLE
[Suggestion] Split with mouse click

### ISSUE THREAD

**Issue by Darkhand81** [RealDebugMonkey/ZeachCobbler#74]
While the new grazer does have its quirks, it does a fantastic job.  I can easily get onto the bottom of the leaderboard with the grazer alone.  However, I've often found myself disabling the grazer, making an opportunistic split, then babysitting until I merge and then resume the grazer.

I'd love to see the ability to split with a mouse click (while in grazer mode).  Clicking the mouse would split in the direction that the mouse is pointed, then either immediately resume grazing or cancel it (because I've noticed that the grazer doesn't handle splits very well, if you split into two blobs they tend to fight each other and you end up not moving.  Having the option to instantly cancel grazing could get around that until the bot can handle splits more smoothly)

Thanks for considering and thanks for a fantastic bot!

**Comment by ghost** [comment]
Good idea, I only wonder if you want to split by mouse click or split by mouse click and stop grazer.

**Comment by ghost** [comment]
And with grazer on is not a big problem, we just need to call the target reset function.

**Comment by Darkhand81** [comment]
Ideally, I'd love to keep the grazer on the entire time. Split in the direction of the mouse pointer on click, and instantly resume grazing. That would allow for some fantastic splits that to an outsider appear like our blob split away from its angle of momentum; to the side, backwards, etc. An enemy in range wouldn't be able to gauge whether we were about to attack.

The only problem I've encountered is that the grazer doesn't handle movement very well when our blob is split; the two halves seem to want to go through each other to get to where they're going, and end up colliding and not moving. That's the only reason I suggested having to option to cancel the grazer, to get around that problem.

**Comment by ghost** [comment]
#75

**Comment by RealDebugMonkey** [comment]
A million thanks to PepinCZ for implementing. 
Code is merged. Closing issue.

**Comment by PepinCZ** [comment]
hahaha tkanks @RealDebugMonkey :+1:
