### ISSUE TITLE
Grazer loses track of destroyed pellet

### ISSUE THREAD

**Issue by smurfix** [RealDebugMonkey/ZeachCobbler#76]
Sometimes the system loses track of having consumed a pellet, which means that the grazer gets stuck on top of it.

Possible workaround: if the thing is inside "me" for >0.2 seconds, destroy it.

**Comment by smurfix** [comment]
just saw the same thing happen with my own blob, after a merge one half was left on the screen. That's very ugly because if the focus is still on that dead blob you can't move away any more. Forced me to abort the game. :-/

**Comment by ghost** [comment]
If i understanding you right, the problem is known. Sometimes the food or blob its eaten or disconnected but in the mod it staying in the items so the Grazer wants to eat it and get stuck on it. I dont really know how to fix it. But the workaround for Grazer could work.

**Comment by smurfix** [comment]
It's not just staying in the mod's items, these do show up on the screen. Maybe an uncaught error, or something along these lines?

**Comment by ghost** [comment]
@smurfix yes, ur right, the're staying on the screen.

**Comment by RealDebugMonkey** [comment]
@smurfix I'm guessing that the pull request I just merged was for this issue?

**Comment by smurfix** [comment]
Yep.
